version: "3"
services:
  pg-container:
    image: postgres:13.3
    container_name: pg-container
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U pguser -d postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  short-link-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
       - pg-container
#          condition: service_healthy